In [1]:
import pandas as pd

In [2]:
Gateway=pd.read_csv("/content/gateway.csv")

In [3]:
Ledger=pd.read_csv("/content/ledger.csv")

## Check for Duplicates and Null Values

In [4]:
print('--- Gateway DataFrame ---')
print('Number of duplicate rows in Gateway:', Gateway.duplicated().sum())
print('\nNumber of null values per column in Gateway:')
print(Gateway.isnull().sum())

print('\n--- Ledger DataFrame ---')
print('Number of duplicate rows in Ledger:', Ledger.duplicated().sum())
print('\nNumber of null values per column in Ledger:')
print(Ledger.isnull().sum())

--- Gateway DataFrame ---
Number of duplicate rows in Gateway: 0

Number of null values per column in Gateway:
transaction_id      0
transaction_date    0
merchant_id         0
amount_usd          0
status              0
payment_method      0
dtype: int64

--- Ledger DataFrame ---
Number of duplicate rows in Ledger: 0

Number of null values per column in Ledger:
transaction_id      0
transaction_date    0
merchant_id         0
amount_usd          0
status              0
payment_method      0
dtype: int64

## Comparing Gateway and Ledger DataFrames

In [5]:
# Find transactions in Ledger that are not in Gateway based on 'transaction_id'
missing_in_gateway = Ledger[~Ledger['transaction_id'].isin(Gateway['transaction_id'])]

print('Records from Ledger missing in Gateway:')
display(missing_in_gateway)

Records from Ledger missing in Gateway:

,transaction_id,transaction_date,merchant_id,amount_usd,status,payment_method
3,R004,2026-03-02,M003,2100.0,success,Card
9,R010,2026-03-05,M004,2500.0,success,Wallet

## Records from Gateway missing in Ledger

In [6]:
# Find transactions in Gateway that are not in Ledger based on 'transaction_id'
missing_in_ledger = Gateway[~Gateway['transaction_id'].isin(Ledger['transaction_id'])]

print('Records from Gateway missing in Ledger:')
display(missing_in_ledger)

Records from Gateway missing in Ledger:

,transaction_id,transaction_date,merchant_id,amount_usd,status,payment_method
8,R011,2026-03-05,M003,1800.0,success,Card

In [18]:
import pandas as pd

# Define USD to INR conversion rate (for robustness if this cell is run independently)
USD_TO_INR_RATE = 83.0

# Ensure amount_mismatches has the INR columns for calculation
# This block is defensive in case the previous cell was not run, or run without INR calculation.
if 'amount_inr_gateway' not in amount_mismatches.columns or 'amount_inr_ledger' not in amount_mismatches.columns:
    amount_mismatches['amount_inr_gateway'] = amount_mismatches['amount_usd_gateway'] * USD_TO_INR_RATE
    amount_mismatches['amount_inr_ledger'] = amount_mismatches['amount_usd_ledger'] * USD_TO_INR_RATE

# Calculate total absolute mismatched amount in INR
total_mismatched_amount_inr = (amount_mismatches['amount_inr_gateway'] - amount_mismatches['amount_inr_ledger']).abs().sum()

# Create a summary report DataFrame
report_data = {
    'Mismatch Type': [
        'Records Missing in Gateway',
        'Records Missing in Ledger',
        'Amount Mismatches',
        'Status Mismatches',
        'Total Mismatched Amount (INR)' # New row for INR summary
    ],
    'Count': [
        len(missing_in_gateway),
        len(missing_in_ledger),
        len(amount_mismatches), # Count of transactions with amount mismatches
        len(status_mismatches),
        total_mismatched_amount_inr # Monetary sum of absolute differences in INR
    ],
    'Details File': [
        'missing_in_gateway.xlsx',
        'missing_in_ledger.xlsx',
        'amount_mismatches.xlsx',
        'status_mismatches.xlsx',
        'amount_mismatches.xlsx' # This file will now contain INR details
    ]
}

reconciliation_report = pd.DataFrame(report_data)

print('Consolidated Reconciliation Report:')
display(reconciliation_report)

Consolidated Reconciliation Report:

                   Mismatch Type   Count             Details File
0     Records Missing in Gateway     2.0  missing_in_gateway.xlsx
1      Records Missing in Ledger     1.0   missing_in_ledger.xlsx
2              Amount Mismatches     2.0   amount_mismatches.xlsx
3              Status Mismatches     1.0   status_mismatches.xlsx
4  Total Mismatched Amount (INR)  7470.0   amount_mismatches.xlsx

In [ ]:
reconciliation_report.to_excel('final_reconciliation_report.xlsx', index=False)
print('final_reconciliation_report.xlsx has been created and updated.')

In [19]:
# Convert the reconciliation report to JSON format
reconciliation_report_json = reconciliation_report.to_json(orient='records', indent=4)

# Save the JSON data to a file
with open('final_reconciliation_report.json', 'w') as f:
    f.write(reconciliation_report_json)

print('final_reconciliation_report.json has been created.')

final_reconciliation_report.json has been created.

In [20]:
print('Consolidated Reconciliation Report:')
display(reconciliation_report)

Consolidated Reconciliation Report:

                   Mismatch Type   Count             Details File
0     Records Missing in Gateway     2.0  missing_in_gateway.xlsx
1      Records Missing in Ledger     1.0   missing_in_ledger.xlsx
2              Amount Mismatches     2.0   amount_mismatches.xlsx
3              Status Mismatches     1.0   status_mismatches.xlsx
4  Total Mismatched Amount (INR)  7470.0   amount_mismatches.xlsx

In [21]:
reconciliation_report.to_excel('final_reconciliation_report.xlsx', index=False)
print('final_reconciliation_report.xlsx has been created and updated.')

final_reconciliation_report.xlsx has been created and updated.

In [22]:
import json

with open('/content/api_response_sample.json', 'r') as f:
    api_response_data = json.load(f)

print('Content of api_response_sample.json:')
display(api_response_data)

Content of api_response_sample.json:

{'generated_at': '2026-03-07T10:00:00Z',
 'source': 'QuickPay Settlement API',
 'batches': [{'batch_id': 'B001',
   'merchant': {'merchant_id': 'M001',
    'merchant_name': 'Alpha Mart',
    'region': 'APAC'},
   'settlements': [{'settlement_id': 'S001',
     'amount_usd': 1520.5,
     'status': 'settled',
     'processed_at': '2026-03-07T08:10:00Z',
     'bank': {'name': 'Bank A', 'country': 'IN'}},
    {'settlement_id': 'S002',
     'amount_usd': 980.0,
     'status': 'pending',
     'processed_at': '2026-03-07T08:45:00Z',
     'bank': {'name': 'Bank A', 'country': 'IN'}},
    {'settlement_id': 'S003',
     'amount_usd': 640.0,
     'status': 'settled',
     'processed_at': '2026-03-07T09:15:00Z',
     'bank': {'name': 'Bank B', 'country': 'SG'}}]},
  {'batch_id': 'B002',
   'merchant': {'merchant_id': 'M004',
    'merchant_name': 'Delta Travels',
    'region': 'US'},
   'settlements': [{'settlement_id': 'S004',
     'amount_usd': 2100.0,
     'status': 'settled',
     'processed_at': '2026-03-07T08:20:00Z',
     'bank': {'name': 'Bank C', 'country': 'US'}},
    {'settlement_id': 'S005',
     'amount_usd': 500.0,
     'status': 'failed',
     'processed_at': '2026-03-07T08:50:00Z',
     'bank': {'name': 'Bank C', 'country': 'US'}},
    {'settlement_id': 'S006',
     'amount_usd': 7200.0,
     'status': 'settled',
     'processed_at': '2026-03-07T09:30:00Z',
     'bank': {'name': 'Bank C', 'country': 'US'}}]}]}

In [25]:
from pandas import json_normalize

# Assuming the 'batches' key contains the list of records to be flattened.
# The previous error indicated 'transactions' key not found within each batch.
# We will now try to flatten the 'batches' directly, assuming each element is a record
# and that transaction details are present directly within these batch objects, or nested within them.
if 'batches' in api_response_data and isinstance(api_response_data['batches'], list):
    flattened_data = json_normalize(
        data=api_response_data['batches'],
        errors='ignore' # Keep errors ignore for any other potential issues during flattening
    )
    print('\nFlattened API Response Data:')
    display(flattened_data.head())
else:
    print("Could not find 'batches' key or it is not a list in api_response_data. Displaying raw data:")
    display(api_response_data)

Flattened API Response Data:

,batch_id,settlements,merchant.merchant_id,merchant.merchant_name,merchant.region
0,B001,"[{'settlement_id': 'S001', 'amount_usd': 1520....",M001,Alpha Mart,APAC
1,B002,"[{'settlement_id': 'S004', 'amount_usd': 2100....",M004,Delta Travels,US

In [26]:
# Clean column names: replace '.' with '_' to avoid issues with attribute access
flattened_data.columns = flattened_data.columns.str.replace('.', '_', regex=False)

print('\nColumn names after cleaning:')
display(flattened_data.columns.tolist())
print('\nFirst 5 rows with cleaned column names:')
display(flattened_data.head())

Column names after cleaning:

['batch_id',
 'settlements',
 'merchant_merchant_id',
 'merchant_merchant_name',
 'merchant_region']

First 5 rows with cleaned column names:

,batch_id,settlements,merchant_merchant_id,merchant_merchant_name,merchant_region
0,B001,"[{'settlement_id': 'S001', 'amount_usd': 1520....",M001,Alpha Mart,APAC
1,B002,"[{'settlement_id': 'S004', 'amount_usd': 2100....",M004,Delta Travels,US

### Flattening 'settlements' data and converting date/time fields

In [28]:
from pandas import json_normalize

# Flatten the 'settlements' column directly from the api_response_data['batches']
# Use record_path to specify the nested list and meta to include parent keys
settlements_df = json_normalize(
    data=api_response_data['batches'],
    record_path=['settlements'],
    meta=[
        'batch_id',
        'merchant_merchant_id',
        'merchant_merchant_name',
        'merchant_region'
    ],
    errors='ignore'
)

# Clean column names: replace '.' with '_' to avoid issues with attribute access
settlements_df.columns = settlements_df.columns.str.replace('.', '_', regex=False)

print('\nFlattened Settlements Data (first 5 rows):')
display(settlements_df.head())
print('\nInfo about Flattened Settlements Data:')
settlements_df.info()

Flattened Settlements Data (first 5 rows):

,settlement_id,amount_usd,status,processed_at,bank_name,bank_country,batch_id,merchant_merchant_id,merchant_merchant_name,merchant_region
0,S001,1520.5,settled,2026-03-07T08:10:00Z,Bank A,IN,B001,NaN,NaN,NaN
1,S002,980.0,pending,2026-03-07T08:45:00Z,Bank A,IN,B001,NaN,NaN,NaN
2,S003,640.0,settled,2026-03-07T09:15:00Z,Bank B,SG,B001,NaN,NaN,NaN
3,S004,2100.0,settled,2026-03-07T08:20:00Z,Bank C,US,B002,NaN,NaN,NaN
4,S005,500.0,failed,2026-03-07T08:50:00Z,Bank C,US,B002,NaN,NaN,NaN

Info about Flattened Settlements Data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   settlement_id           6 non-null      object
 1   amount_usd              6 non-null      float64
 2   status                  6 non-null      object
 3   processed_at            6 non-null      object
 4   bank_name               6 non-null      object
 5   bank_country            6 non-null      object
 6   batch_id                6 non-null      object
 7   merchant_merchant_id    0 non-null      object
 8   merchant_merchant_name  0 non-null      object
 9   merchant_region         0 non-null      object
dtypes: float64(1), object(9)
memory usage: 612.0+ bytes

In [32]:
# Identify and convert date/time columns in settlements_df
# Assuming columns ending with '_at' or containing 'date' or 'time' are date/time fields

for col in settlements_df.columns:
    if 'date' in col or 'time' in col or col.endswith('_at'):
        try:
            # Convert to datetime and then make it timezone-naive if it has a timezone
            temp_series = pd.to_datetime(settlements_df[col], errors='coerce')
            if temp_series.dt.tz is not None:
                settlements_df[col] = temp_series.dt.tz_localize(None)
                print(f"Converted '{col}' to datetime and removed timezone.")
            else:
                settlements_df[col] = temp_series
                print(f"Converted '{col}' to datetime.")
        except Exception as e:
            print(f"Could not convert '{col}' to datetime: {e}")

print('\nInfo about Flattened Settlements Data after date conversion:')
settlements_df.info()

print('\nFlattened Settlements Data with converted dates (first 5 rows):')
display(settlements_df.head())

Converted 'processed_at' to datetime and removed timezone.

Info about Flattened Settlements Data after date conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   settlement_id           6 non-null      object
 1   amount_usd              6 non-null      float64
 2   status                  6 non-null      object
 3   processed_at            6 non-null      datetime64[ns]
 4   bank_name               6 non-null      object
 5   bank_country            6 non-null      object
 6   batch_id                6 non-null      object
 7   merchant_merchant_id    0 non-null      object
 8   merchant_merchant_name  0 non-null      object
 9   merchant_region         0 non-null      object
dtypes: datetime64[ns](1), float64(1), object(8)
memory usage: 612.0+ bytes

Flattened Settlements Data with converted dates (first 5 rows):

,settlement_id,amount_usd,status,processed_at,bank_name,bank_country,batch_id,merchant_merchant_id,merchant_merchant_name,merchant_region
0,S001,1520.5,settled,2026-03-07 08:10:00,Bank A,IN,B001,NaN,NaN,NaN
1,S002,980.0,pending,2026-03-07 08:45:00,Bank A,IN,B001,NaN,NaN,NaN
2,S003,640.0,settled,2026-03-07 09:15:00,Bank B,SG,B001,NaN,NaN,NaN
3,S004,2100.0,settled,2026-03-07 08:20:00,Bank C,US,B002,NaN,NaN,NaN
4,S005,500.0,failed,2026-03-07 08:50:00,Bank C,US,B002,NaN,NaN,NaN

In [33]:
output_excel_path = 'normalized_api_settlements.xlsx'
settlements_df.to_excel(output_excel_path, index=False)
print(f"Normalized API settlement data saved to '{output_excel_path}'")

Normalized API settlement data saved to 'normalized_api_settlements.xlsx'